on:
  push:
    branches:
      - kovan

name: Deploy kovan to VM

jobs:
  deploy:
    name: Deploy Kovan
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
       ETHEREUM_RPC: ${{secrets.ETHEREUM_RPC_KOVAN}}
       POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
       NETWORK: ${{secrets.NETWORK}}
      with:
        host: ${{secrets.DEPLOY_KOVAN_URL}}
        username: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        envs: ETHEREUM_RPC,POSTGRES_PASSWORD,NETWORK
        script: |
          if docker container ls | grep -q graph-node
          then 
          echo "Redeploy subgraph only..."
          cd geb-subgraph/docker
          docker-compose stop graph-node postgres
          git checkout kovan
          git pull
          sudo chmod -R +rwx data/
          docker-compose up --build graph-deployer
          else
          echo "Redeploy all..."
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          sudo rm -rf geb-subgraph
          git clone https://github.com/reflexer-labs/geb-subgraph
          git checkout kovan
          cd geb-subgraph/docker
          echo ETHEREUM_RPC=$ETHEREUM_RPC >> .env
          echo NETWORK=$NETWORK >> .env
          echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
          docker-compose up --build -d
          fi
   
